/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 19/01/2025 11:21:51
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     168000000
#define MX_SYSCLKFreq_VALUE                     168000000
#define MX_HCLKFreq_Value                       168000000
#define MX_FCLKCortexFreq_Value                 168000000
#define MX_CortexFreq_Value                     168000000
#define MX_AHBFreq_Value                        168000000
#define MX_APB1Freq_Value                       42000000
#define MX_APB2Freq_Value                       84000000
#define MX_APB1TimFreq_Value                    84000000
#define MX_APB2TimFreq_Value                    168000000
#define MX_48MHZClocksFreq_Value                84000000
#define MX_EthernetFreq_Value                   168000000
#define MX_LCDTFTFreq_Value                     12250000
#define MX_I2SClocksFreq_Value                  96000000
#define MX_SAI_AClocksFreq_Value                12250000
#define MX_SAI_BClocksFreq_Value                12250000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    168000000

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA0/WKUP */
#define MX_PA0_WKUP_Pin                         PA0_WKUP
#define MX_PA0_WKUP_GPIOx                       GPIOA
#define MX_PA0_WKUP_GPIO_PuPd                   GPIO_NOPULL
#define MX_BUTTON_N                             PA0_WKUP
#define MX_PA0_WKUP_GPIO_Pin                    GPIO_PIN_0
#define MX_PA0_WKUP_GPIO_ModeDefaultEXTI        GPIO_MODE_IT_RISING

/* Pin PG13 */
#define MX_PG13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PG13_Pin                             PG13
#define MX_PG13_GPIOx                           GPIOG
#define MX_PG13_PinState                        GPIO_PIN_RESET
#define MX_PG13_GPIO_PuPd                       GPIO_NOPULL
#define MX_LED0                                 PG13
#define MX_PG13_GPIO_Pin                        GPIO_PIN_13
#define MX_PG13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PG14 */
#define MX_PG14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PG14_Pin                             PG14
#define MX_PG14_GPIOx                           GPIOG
#define MX_PG14_PinState                        GPIO_PIN_RESET
#define MX_PG14_GPIO_PuPd                       GPIO_NOPULL
#define MX_LED1                                 PG14
#define MX_PG14_GPIO_Pin                        GPIO_PIN_14
#define MX_PG14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

